// [MANSI] Certificate field mapping.
//
// What this is for: defines which Batch/Harvester fields map to which
// certificate field + display label, structured around WHO GACP / EU-style
// traceability documentation. Does NOT generate the PDF itself -- that's
// api/certificate/route.ts.
//
// IMPORTANT: this app does not grant real regulatory certification. The
// generated PDF must carry a disclaimer saying so -- see disclaimerText.
//
// Depends on: src/lib/types.ts -- CertificateData (Batch + Harvester).
// Blocks: src/app/api/certificate/route.ts (Mansi) -- the PDF layout reads this file's field list.
//
// Must output/return: CERTIFICATE_FIELDS (ordered field key/label/getValue
// list) and disclaimerText.
//
// TODO (Mansi):
// 1. Research real WHO GACP / EU herbal traceability fields to confirm this list is realistic.
// 2. Fill in display labels for each field.
// 3. Write disclaimerText clearly stating this is a demo/prototype document, not an official certificate.
// 4. Confirm field names line up once api/certificate/route.ts is built.

import type { CertificateData } from "@/lib/types";
import { getStandardPlantPart } from "@/data/demoHerbs";

export type CertificateField = {
  key: string;
  label: string;
  section?: "identity" | "botanical" | "origin" | "verification" | "crypto";
  getValue: (data: CertificateData) => string;
};

export const CERTIFICATE_FIELDS: CertificateField[] = [
  {
    key: "certificate_id",
    label: "Certificate ID",
    section: "identity",
    getValue: (data) => `CERT-${data.batch.id.slice(0, 8).toUpperCase()}`,
  },
  {
    key: "batch_id",
    label: "Batch Tracking ID",
    section: "identity",
    getValue: (data) => data.batch.id,
  },
  {
    key: "herb_name",
    label: "Botanical / Herb Name",
    section: "botanical",
    getValue: (data) => data.batch.species_claimed,
  },
  {
    key: "plant_part",
    label: "Official Plant Part (GACP)",
    section: "botanical",
    getValue: (data) => getStandardPlantPart(data.batch.species_claimed),
  },
  {
    key: "source_location",
    label: "Collection GPS Coordinates",
    section: "origin",
    getValue: (data) =>
      `${data.batch.gps_lat.toFixed(5)}° N, ${data.batch.gps_lon.toFixed(5)}° E`,
  },
  {
    key: "harvest_date",
    label: "Harvest Date & Time",
    section: "origin",
    getValue: (data) => {
      try {
        const d = new Date(data.batch.timestamp);
        return (
          d.toLocaleDateString("en-GB", {
            day: "2-digit",
            month: "short",
            year: "numeric",
            hour: "2-digit",
            minute: "2-digit",
            timeZone: "UTC",
          }) + " UTC"
        );
      } catch {
        return data.batch.timestamp;
      }
    },
  },
  {
    key: "collector",
    label: "Collector / Harvester",
    section: "origin",
    getValue: (data) =>
      `${data.harvester.name} (Harvester ID: ${data.harvester.id.slice(0, 8).toUpperCase()})`,
  },
  {
    key: "quantity",
    label: "Batch Lot Quantity",
    section: "botanical",
    getValue: (data) =>
      data.batch.payment_amount
        ? `1 Certified Lot (Valuation: ₹${data.batch.payment_amount})`
        : "1 Certified Harvest Lot (Standard Unit)",
  },
  {
    key: "verification",
    label: "Quality Control & AI Verification",
    section: "verification",
    getValue: (data) =>
      `QC: ${data.batch.qc_status.toUpperCase()} | AI Match: ${data.batch.species_ai_result} (${(data.batch.confidence_score * 100).toFixed(1)}% confidence)${
        data.batch.qc_notes ? ` | Notes: ${data.batch.qc_notes}` : ""
      }`,
  },
  {
    key: "timestamp",
    label: "Certificate Generation Timestamp",
    section: "verification",
    getValue: (data) => {
      try {
        const d = new Date(data.generated_at);
        return (
          d.toLocaleDateString("en-GB", {
            day: "2-digit",
            month: "short",
            year: "numeric",
            hour: "2-digit",
            minute: "2-digit",
            second: "2-digit",
            timeZone: "UTC",
          }) + " UTC"
        );
      } catch {
        return data.generated_at;
      }
    },
  },
  {
    key: "hash",
    label: "SHA-256 Tamper-Evident Ledger Hash",
    section: "crypto",
    getValue: (data) => data.batch.hash,
  },
  {
    key: "prev_hash",
    label: "Previous Batch Link Hash",
    section: "crypto",
    getValue: (data) =>
      data.batch.prev_hash ?? "GENESIS_ROOT (Initial Batch in Chain)",
  },
];

export const disclaimerText =
  "PROTOTYPE / DEMONSTRATION DOCUMENT ONLY: This document is an automated digital Certificate of Origin and Traceability generated by RootCode HerbTrace for prototype demonstration. RootCode demonstrates traceability principles and does not represent regulatory certification. AI identification should be confirmed by an authorized human before final certification. Designed with reference to WHO GACP (Good Agricultural and Collection Practices) and EU herbal traceability reference guidelines. Tamper-evidence is established via SHA-256 digital cryptographic hash chaining.";


